name: Build and release python 3

on:
  push:
    branches: [celery-5]
  pull_request:
    branches: [celery-5]


jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suite:
          [
            unit,
            functional_wsp,
            functional_arxiv,
            functional_desy,
            functional_cds,
            functional_pos,
            functional_elsevier,
            functional_aps
          ]
        python-version: ["3.9", "3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel coveralls check-manifest
          pip install -e .[tests]

      - name: Show python dependencies
        run: |
          pip freeze

      - name: Install dependencies
        run: |
          docker-compose -f docker-compose.deps.py3.yml build
          docker-compose -f docker-compose.test.py3.yml run --rm scrapyd-deploy

      - name: Print logs if failure
        if: ${{ failure() }}
        run: |
          docker-compose -f docker-compose.test.py3.yml logs --tail=200

      - name: Run tests
        run: |
          docker-compose -f docker-compose.test.py3.yml run --rm ${{ matrix.suite }}

      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@v20201129
        with:
          parallel: true
          github-token: ${{ secrets.github_token }}
          flag-name: run-${{ matrix.test_number }}

  Coveralls:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: AndreMiras/coveralls-python-action@v20201129
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
