name: Test python 3

on:
  push:
    branches: [celery-5]
  pull_request:
    branches: [celery-5]


jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[all]

      - name: Show python dependencies
        run: |
          pip freeze

      - name: Run tests
        run: |
          py.test -vv tests/unit
